type CompanyType {
  id: String
  name: String
  description: String
}

type UserType {
  id: String
  firstName: String
  age: Int
  company: CompanyType
}

type Query {
  user(id: String!): UserType
  company(id: String): CompanyType
}

# type Mutation {
#   upvotePost(postId: Int!): Post
# }
