interface ITodo {
    taskId: String
    name: String
    isComplete: Boolean
  }

  type Todo implements ITodo {
    taskId: String
    name: String
    isComplete: Boolean
  }

  type Query {
    todos(todoIdList: [String]): [Todo]
  }