interface ITodo {
  taskId: String
  name: String
  isComplete: Boolean
}

type Todo implements ITodo {
  taskId: String
  name: String
  isComplete: Boolean
}

input TodoInput { 
  name: String
  isComplete: Boolean
}

type Mutation {
  createTodo(input: TodoInput!): Todo
  updateTodo(taskId: ID!, input: TodoInput!): Todo
  toggleTodo(taskId: ID!, isComplete: Boolean!): Todo
}

type Query {
  getTodos(todoIdList: [String]): [Todo]
}